// POST
export const ADD_GAME = "ADD_GAME";
export const ADD_CLASSROOM = "ADD_CLASSROOM";
export const ADD_PLAYER_TO_GAME = "ADD_PLAYER_TO_GAME";

// FETCH
export const FETCH_GAME_BY_ID = "FETCH_GAME_BY_ID";
export const FETCH_GAMES_BY_TEACHER = "FETCH_GAMES_BY_TEACHER";
export const FETCH_CLASSROOMS_BY_TEACHER = "FETCH_CLASSROOMS_BY_TEACHER";

// REMOVE
export const REMOVE_CURRENT_GAME = "REMOVE_CURRENT_GAME";
